version: 2.1
orbs:
  jira: circleci/jira@1.3.1
jobs:
  build:
    docker:
      - image: 'circleci/node:10'
    steps:
      - run: echo "hello"
orbs:
  jira: circleci/jira@x.y.z
version: 2.1
workflows:
  build:
    jobs:
      - build:
          post-steps:
            - jira/notify

